import { useState } from "react";
import { Link } from "react-router-dom";
import { toast } from "sonner";
import { useData } from "@/context/DataContext";
import { fmtMoney } from "@/lib/api";

const FILTERS = [
  ["all", "All"],
  ["quick", "Quick Wins"],
  ["infrastructure", "Infrastructure"],
  ["renewables", "Renewables"],
  ["behaviour", "Behaviour"],
];

const badgeClass = (p) => (p === "high" ? "high" : p === "medium" ? "medium" : "low");

export default function Recommendations() {
  const { latest, currency, favourites, toggleFavourite } = useData();
  const [filter, setFilter] = useState("all");

  if (!latest)
    return (
      <section className="view-section">
        <div className="glass-card empty-state" data-testid="recommendations-empty">
          <i className="fa-solid fa-lightbulb" />
          <h3>No recommendations yet</h3>
          <p style={{ margin: "0.75rem 0 1.75rem" }}>Aira generates tailored actions once you complete an energy audit.</p>
          <Link to="/analysis" className="btn btn-primary" data-testid="recommendations-empty-cta">
            <i className="fa-solid fa-atom" /> Run Energy Analysis
          </Link>
        </div>
      </section>
    );

  const recs = latest.insights?.recommendations || [];
  const shown = filter === "all" ? recs : recs.filter((r) => (r.category || "quick").toLowerCase() === filter);
  const favTitles = new Set(favourites.map((f) => f.title));

  const onFav = async (r) => {
    const added = await toggleFavourite({ title: r.title, detail: r.detail, category: r.category, monthlySaving: r.monthlySaving });
    toast.success(added ? "Saved to favourites" : "Removed from favourites");
  };

  return (
    <section className="view-section" data-testid="recommendations-page">
      <div className="recommendations-header">
        <div>
          <span className="hero-tagline">Actionable Guidance</span>
          <h2 style={{ fontSize: "2rem" }}>Tailored Energy Recommendations</h2>
          <p style={{ color: "var(--color-gray-400)", fontSize: "0.9rem" }}>
            {recs.length} actions generated by Aira{latest.insights?.aiGenerated ? " (Gemini)" : ""} · total upside{" "}
            {fmtMoney(recs.reduce((s, r) => s + Number(r.monthlySaving || 0), 0), currency)} / month
          </p>
        </div>
        <div className="rec-filters">
          {FILTERS.map(([k, label]) => (
            <button key={k} className={`rec-filter-btn ${filter === k ? "active" : ""}`} onClick={() => setFilter(k)} data-testid={`rec-filter-${k}`}>
              {label}
            </button>
          ))}
        </div>
      </div>

      {latest.insights?.summary && (
        <div className="glass-card" style={{ marginBottom: "1.75rem" }} data-testid="recommendations-summary">
          <h3 className="card-title">
            <i className="fa-solid fa-wand-magic-sparkles" /> Aira's Executive Summary
          </h3>
          <p style={{ fontSize: "0.94rem" }}>{latest.insights.summary}</p>
        </div>
      )}

      <div className="recommendations-grid stagger" data-testid="recommendations-grid">
        {shown.length === 0 && (
          <div className="glass-card" data-testid="recommendations-filter-empty">
            <p>No recommendations in this category. Try another filter.</p>
          </div>
        )}
        {shown.map((r, idx) => (
          <div className="glass-card rec-card interactive" key={`${r.title}-${idx}`} data-testid="recommendation-card">
            <button
              className={`fav-btn ${favTitles.has(r.title) ? "active" : ""}`}
              onClick={() => onFav(r)}
              aria-label="Favourite"
              data-testid="recommendation-fav-btn"
            >
              <i className={favTitles.has(r.title) ? "fa-solid fa-star" : "fa-regular fa-star"} />
            </button>
            <div>
              <span className={`rec-badge ${badgeClass(r.priority)}`}>{r.category || "quick"}</span>
              <h3 className="rec-title">{r.title}</h3>
              <p>{r.detail}</p>
              <div className="rec-meta">
                <span>
                  <i className="fa-regular fa-clock" /> {r.payback || "—"}
                </span>
                <span>
                  <i className="fa-solid fa-screwdriver-wrench" /> {r.effort || "Medium"} effort
                </span>
              </div>
            </div>
            <div className="rec-impact-box">
              <span style={{ color: "var(--color-gray-400)" }}>Estimated savings</span>
              <span className="rec-saving-value">{fmtMoney(r.monthlySaving, currency)} / mo</span>
            </div>
          </div>
        ))}
      </div>

      <div style={{ display: "flex", justifyContent: "center", gap: "1.25rem", marginTop: "2.5rem", flexWrap: "wrap" }}>
        <Link to="/report" className="btn btn-primary" data-testid="recommendations-to-report">
          <i className="fa-solid fa-file-contract" /> Generate Health Report
        </Link>
        <Link to="/chat" className="btn btn-secondary" data-testid="recommendations-to-chat">
          <i className="fa-regular fa-comment-dots" /> Ask Aira about these
        </Link>
      </div>
    </section>
  );
}
